[project]
name = "music"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Kyle Kestell", email = "kyle@kestell.org"},
]
dependencies = ["pyside6>=6.8.0.2", "musicbrainzngs>=0.7.1", "aioslsk>=1.4.1", "dateparser>=1.2.0", "qasync>=0.27.1", "aiosqlite>=0.20.0", "fuzzywuzzy>=0.18.0", "python-Levenshtein>=0.26.1"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "BSD0"}


[tool.pdm]
distribution = false
